[tool.poetry]
name = "chess_engine"
version = "0.1.0"
description = "Chess Engine module for PlayPal using Stockfish and FastMCP"
authors = ["PlayPal Team"]
readme = "README.md"
packages = [
    { include = "src", from = "." }
]
license = "MIT"
repository = "https://github.com/yourusername/dylangames-mcp-chess-engine"
keywords = ["chess", "stockfish", "mcp", "playpal"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Topic :: Games/Entertainment :: Board Games",
]

[tool.poetry.dependencies]
python = "^3.10"
fastapi = "^0.109.2"
mcp = {version = "^1.2.0", extras = ["cli"]}
python-chess = "^1.999"
setuptools = "^69.2.0"

[tool.poetry.group.dev.dependencies]
pytest = "^7.4.0"
black = "^24.2.0"
flake8 = "^7.0.0"
flake8-docstrings = "^1.7.0"
isort = "^5.13.2"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
chess-engine = "src.main:main"

[tool.black]
line-length = 100
target-version = ['py310']
include = '\.pyi?$'

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 100

[tool.flake8]
max-line-length = 100
extend-ignore = "E203"
docstring-convention = "google"
exclude = [".git", "__pycache__", "build", "dist"]
